### ISSUE TITLE
Bug - Error detected

### ISSUE THREAD

**Issue by tigerjack** [lygaret/autohighlight.vim#3]
As per the title, the plugin give me an annoying error message.

    Error detected while processing function <SNR>59_clear:
    line    2:
    E803: ID not found: 4

I'm using Vim 8.0.

**Comment by jounathaen** [comment]
Can confirm, same for me

**Comment by lygaret** [comment]
this repository is abandoned, please check out @ZwodahS fork for improvements, sorry.
